version: '3'
services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb-new
    # command: keydb-server /etc/keydb/redis.conf --server-threads 2 --active-replica yes --replicaof 192.168.1.1 6379
    # command: keydb-server /etc/keydb/redis.conf --server-threads 2 --active-replica yes --replicaof 192.168.1.2 6379
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    volumes:
      - ./redis.conf:/etc/keydb/redis.conf
      - data:/data
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  data:
    driver: local
